use rocket::data::{FromData, Outcome, ToByteUnit};
use rocket::http::{ContentType, Status};
use rocket::outcome::Outcome::{Failure, Forward, Success};
use rocket::{Data, Request};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;

pub mod checkout;
pub mod client;
pub mod item;
pub mod login;
pub mod order;
pub mod order_status;
pub mod payment_method;
pub mod product;
pub mod response;
pub mod rule;
pub mod service;
pub mod user;
